import { createRequire } from "node:module";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import assert from "node:assert/strict";
import { STORAGE_KEY } from "../src/state.js";
import { SCENARIOS } from "../src/narrative.js";
const root = fileURLToPath(new URL("../", import.meta.url));
const require = createRequire(path.join(process.env.NODE_WORKSPACE || "C:/Users/Typelin_Station/.workbuddy-ai/binaries/node/workspace", "package.json"));
const { chromium } = require("playwright");
const output = path.join(root, "outputs");
const records = [], errors = [];
const pass = (name, detail = "passed") => { records.push({ name, passed: true, detail }); console.log(`PASS ${name}: ${detail}`); };
const server = spawn(process.execPath, [path.join(root, "scripts/serve.mjs"), "--production"], { env: { ...process.env, PORT: "4183" }, stdio: ["ignore", "pipe", "pipe"] });
let browser;
try {
  await new Promise((resolve, reject) => { server.stdout.once("data", resolve); server.once("error", reject); server.once("exit", code => reject(new Error(`Server exit: ${code}`))); });
  browser = await chromium.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true, colorScheme: "light" });
  const page = await context.newPage();
  const observe = page => { page.on("pageerror", e => errors.push(e.message)); page.on("console", m => { if (m.type() === "error") errors.push(m.text()); }); };
  observe(page);
  const url = "http://127.0.0.1:4183";
  await page.goto(url, { waitUntil: "networkidle" });
  const stage = () => page.locator("#app").getAttribute("data-stage");
  const state = () => page.evaluate(key => JSON.parse(localStorage.getItem(key)), STORAGE_KEY);
  const settled = async () => { await page.waitForTimeout(2050); };
  const shot = async name => { await page.evaluate(() => document.activeElement?.blur()); await page.screenshot({ path: path.join(output, `v2-${name}.png`) }); };
  const go = async n => { await page.locator(`[data-step='${n}']`).click(); await settled(); assert.equal(await stage(), String(n)); };
  assert.equal(await stage(), "0");
  assert.equal(await page.locator("#threads path").count(), 96); pass("production loads 96 thread instrument");
  await shot("01");
  const desktopFont = await page.locator(".body-copy").first().evaluate(e => parseFloat(getComputedStyle(e).fontSize));
  assert.ok(desktopFont >= 17); pass("desktop readable body type", `${desktopFont}px`);
  const box = await page.locator("#instrument").boundingBox();
  const width = Math.min(box.width / 800, box.height / 660) * 800;
  const left = box.x + (box.width - width) / 2;
  async function dragTo(x) {
    await page.mouse.move(left + width * .5, box.y + box.height * .5); await page.mouse.down();
    await page.mouse.move(left + width * x, box.y + box.height * .5, { steps: 14 }); await page.mouse.up(); await settled();
  }
  await dragTo(.1);
  assert.equal(await page.locator("#app").getAttribute("data-approach"), "clear");
  const leftTitle = await page.locator("#answer-title").textContent();
  const leftPath = await page.locator("#threads path").first().getAttribute("d");
  await shot("drag-left");
  await dragTo(.9);
  assert.equal(await page.locator("#app").getAttribute("data-approach"), "creative");
  assert.notEqual(await page.locator("#answer-title").textContent(), leftTitle);
  assert.notEqual(await page.locator("#threads path").first().getAttribute("d"), leftPath);
  await shot("drag-right"); pass("real drag changes both geometry and concrete proposal");
  const count = (await state()).traces.length;
  await page.mouse.move(200, 450); await page.mouse.wheel(0, await page.locator('#story-1').evaluate(el => el.getBoundingClientRect().top - 145)); await settled();
  assert.equal(await stage(), "1"); assert.equal((await state()).traces.length, count);
  pass("native wheel advances without fabricated gesture traces"); await shot("02");
  await page.mouse.wheel(0, await page.locator('#story-2').evaluate(el => el.getBoundingClientRect().top - 145)); await settled(); assert.equal(await stage(), "2");
  await page.locator("#instrument").focus(); await page.keyboard.press("x"); await settled();
  assert.ok((await state()).scars.some(s => s.source === "gesture"));
  pass("keyboard counterexample records human input"); await shot("03");
  await go(3); await shot("04");
  const constrained = await state();
  const constraintText = await page.locator("#constraint-memory").textContent();
  assert.ok(SCENARIOS[constrained.scenario].constraints.every(item => constraintText.includes(item)));
  assert.ok(await page.locator("#constraint-memory").isVisible());
  const proposal = await page.locator("#answer-title").textContent();
  await page.locator("#secondary-action").click(); await settled();
  assert.notEqual(await page.locator("#answer-title").textContent(), proposal);
  pass("alternative respects constraints and changes answer");
  await go(4); await shot("05");
  const hash = await page.locator("#form-id").textContent();
  const [download] = await Promise.all([page.waitForEvent("download"), page.locator("#primary-action").click()]);
  assert.equal(await download.failure(), null); await download.saveAs(path.join(output, "v2-sample-weave.svg"));
  const svg = await readFile(path.join(output, "v2-sample-weave.svg"), "utf8");
  assert.ok(svg.includes(hash) && svg.includes("proposal") && !svg.includes("NaN")); pass("actual SVG download contains proposal and state", `${Buffer.byteLength(svg)} bytes`);
  await page.reload({ waitUntil: "networkidle" }); await settled();
  assert.equal(await stage(), "4"); assert.equal(await page.locator("#form-id").textContent(), hash); pass("refresh restores chapter and choices");
  await go(1); assert.equal((await state()).scars.length, 1); pass("scroll back preserves accumulated consequences");
  await page.locator("#instrument").focus(); await page.keyboard.down("Space"); await settled();
  assert.ok(await page.locator("#reverse-label").isVisible());
  await page.keyboard.up("Space"); assert.ok(!(await page.locator("#reverse-label").isVisible())); pass("hidden alternative layer");
  await page.emulateMedia({ reducedMotion: "reduce" }); await go(4); await go(0);
  assert.ok(await page.locator("#app").evaluate(e => e.classList.contains("reduced-motion"))); pass("reduced-motion navigation remains complete");
  await page.setViewportSize({ width: 1280, height: 600 }); await go(3); await shot("short");
  const action = await page.locator("#primary-action").boundingBox(); assert.ok(action.y >= 0 && action.y + action.height < 601);
  const panelBox = await page.locator('.answer-panel').boundingBox();
  const constraintBox = await page.locator('#constraint-memory').boundingBox();
  const controlsBox = await page.locator('.device-controls').boundingBox();
  assert.ok(constraintBox.y + constraintBox.height <= panelBox.y + panelBox.height + 1);
  assert.ok(controlsBox.y >= panelBox.y + panelBox.height - 1);
  pass("short viewport controls visible without text overlap");
  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: "reduce" });
  const mobile = await mobileContext.newPage(); observe(mobile);
  await mobile.goto(url, { waitUntil: "networkidle" }); await mobile.waitForTimeout(200);
  assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  const mobileFont = await mobile.locator(".body-copy").first().evaluate(e => parseFloat(getComputedStyle(e).fontSize)); assert.ok(mobileFont >= 16);
  await mobile.screenshot({ path: path.join(output, "v2-mobile.png") }); pass("390px layout and readable body", `${mobileFont}px`);
  const cdp = await mobileContext.newCDPSession(mobile);
  let mb = await mobile.locator("#instrument").boundingBox();
  await cdp.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x: mb.x + mb.width * .45, y: mb.y + mb.height * .5 }] });
  await cdp.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [{ x: mb.x + mb.width * .82, y: mb.y + mb.height * .5 }] });
  await cdp.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  assert.equal(await mobile.locator("#app").getAttribute("data-approach"), "creative"); pass("horizontal touch changes proposal");
  const beforeScroll = await mobile.evaluate(() => scrollY);
  mb = await mobile.locator("#instrument").boundingBox();
  await cdp.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x: 190, y: mb.y + mb.height * .8 }] });
  await cdp.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [{ x: 190, y: mb.y + mb.height * .2 }] });
  await cdp.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  await mobile.waitForTimeout(350); assert.ok(await mobile.evaluate(() => scrollY) > beforeScroll); pass("vertical touch on instrument still scrolls page");
  await mobile.evaluate(() => window.scrollTo(0, document.documentElement.scrollHeight)); await mobile.waitForTimeout(250);
  assert.equal(await mobile.locator("#app").getAttribute("data-stage"), "4");
  const ms = await mobile.evaluate(key => JSON.parse(localStorage.getItem(key)), STORAGE_KEY);
  assert.equal(ms.scars[0].source, "example"); pass("scroll-only completion labels automatic example honestly");
  await mobile.evaluate(() => { const e = document.querySelector('#story-4'); window.scrollTo(0,e.getBoundingClientRect().top+scrollY-410); });
  await mobile.waitForTimeout(200); await mobile.screenshot({ path: path.join(output, "v2-mobile-final.png") });
  await mobile.setViewportSize({ width: 320, height: 568 }); assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); pass("320px no horizontal overflow");
  const scrollOnly = await context.newPage(); observe(scrollOnly);
  await scrollOnly.goto(url); await scrollOnly.locator('[data-step="0"]').click(); await settled();
  const seen = new Set();
  await scrollOnly.mouse.move(220, 500);
  for (let i = 0; i < 20; i++) {
    await scrollOnly.mouse.wheel(0, 340); await scrollOnly.waitForTimeout(110);
    seen.add(await scrollOnly.locator('#app').getAttribute('data-stage'));
  }
  assert.ok(['1','2','3','4'].every(s => seen.has(s)));
  pass("wheel-only full journey visits every stage");
  const constrainedState = await scrollOnly.evaluate(key => JSON.parse(localStorage.getItem(key)), STORAGE_KEY);
  assert.ok(constrainedState.scars.length > 0);
  const portable = await context.newPage(); observe(portable);
  await portable.goto(new URL("../outputs/unfinished-form.html", import.meta.url).href, { waitUntil: "load" });
  assert.equal(await portable.locator("#threads path").count(), 96); pass("single HTML runs offline");
  await portable.locator("#about-open").click(); await portable.keyboard.press("Escape"); assert.ok(!(await portable.locator("#about-dialog").evaluate(e => e.open))); pass("dialog keyboard dismissal");
  assert.deepEqual(errors, []); pass("zero browser errors");
} catch (error) {
  records.push({ name: "failure", passed: false, detail: error.stack }); console.error(error.stack); process.exitCode = 1;
} finally {
  await browser?.close(); server.kill();
  await writeFile(path.join(output, "v2-results.json"), JSON.stringify({ passed: records.every(r => r.passed), tests: records, errors }, null, 2));
}
