import { createRequire } from "node:module";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { readFile, writeFile } from "node:fs/promises";
import assert from "node:assert/strict";
const root = fileURLToPath(new URL("../", import.meta.url));
const require = createRequire(path.join(process.env.NODE_WORKSPACE || "C:/Users/Typelin_Station/.workbuddy-ai/binaries/node/workspace", "package.json"));
const { chromium } = require("playwright");
const output = path.join(root, "outputs");
const rows = [];
const errors = [];
const record = (name, detail = "passed") => { rows.push({ name, passed: true, detail }); console.log(`PASS ${name}: ${detail}`); };
const server = spawn(process.execPath, [path.join(root, "scripts", "serve.mjs"), "--production"], { env: { ...process.env, PORT: "4181" }, stdio: ["ignore", "pipe", "pipe"] });
let browser;
try {
  await new Promise((resolve, reject) => { server.stdout.once("data", resolve); server.once("error", reject); server.once("exit", code => reject(new Error(`Preview exit ${code}`))); });
  browser = await chromium.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true, colorScheme: "light" });
  const page = await context.newPage();
  const observe = page => {
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
  };
  observe(page);
  await page.goto("http://127.0.0.1:4181", { waitUntil: "networkidle" });
  const stage = () => page.locator("#app").getAttribute("data-stage");
  const state = () => page.evaluate(() => JSON.parse(localStorage.getItem("astra-unfinished-form-v1")));
  const next = () => page.locator("#primary-action").click();
  const settle = () => page.waitForTimeout(2450);
  const shot = async name => {
    await page.evaluate(() => document.activeElement?.blur());
    await page.screenshot({ path: path.join(output, `final-${name}.png`), fullPage: true });
  };
  assert.equal(await stage(), "0"); record("production entry");
  await shot("01");
  await next();
  await page.locator("#instrument").focus();
  await page.keyboard.press("ArrowUp"); await page.keyboard.press("ArrowRight");
  assert.equal((await state()).traces.length, 3); record("keyboard trace accumulation");
  await settle(); await shot("02");
  await next(); assert.equal((await state()).scars.length, 0);
  record("fracture requires deliberate input");
  await page.locator("#instrument").focus(); await page.keyboard.press("x");
  assert.equal((await state()).scars.length, 1);
  await settle(); await shot("03");
  await next(); await settle(); await shot("04");
  const beforeAlternate = await page.locator("#threads path").first().getAttribute("d");
  await page.locator("#secondary-action").click(); await settle();
  assert.notEqual(await page.locator("#threads path").first().getAttribute("d"), beforeAlternate);
  record("alternate weaving changes geometry");
  await page.locator("#secondary-action").click(); await settle();
  await next(); await settle(); await shot("05");
  assert.equal(await stage(), "4"); record("five-stage journey");
  const formId = await page.locator("#form-id").textContent();
  const formPath = await page.locator("#threads path").first().getAttribute("d");
  await page.reload({ waitUntil: "networkidle" });
  assert.equal(await page.locator("#form-id").textContent(), formId);
  assert.equal(await page.locator("#threads path").first().getAttribute("d"), formPath);
  record("refresh preserves fingerprint and geometry", formId);
  const [download] = await Promise.all([page.waitForEvent("download"), next()]);
  assert.equal(await download.failure(), null);
  await download.saveAs(path.join(output, "sample-weave.svg"));
  const svg = await readFile(path.join(output, "sample-weave.svg"), "utf8");
  assert.ok(svg.includes(formId) && svg.includes("<metadata>") && !svg.includes("NaN"));
  record("real SVG download", `${download.suggestedFilename()} / ${Buffer.byteLength(svg)} bytes`);
  await page.waitForTimeout(4000);
  await page.locator("#instrument").focus(); await page.keyboard.down("Space"); await settle();
  assert.ok(await page.locator("#app").evaluate(el => el.classList.contains("backside")));
  assert.equal((await state()).reverseFound, true);
  await shot("hidden");
  await page.keyboard.up("Space");
  assert.ok(!(await page.locator("#app").evaluate(el => el.classList.contains("backside"))));
  record("hidden layer hold and release");
  await page.locator("#reset").click(); assert.equal(await stage(), "0"); assert.equal((await state()).traces.length, 0);
  record("reset clears this work only");
  await page.waitForTimeout(4000);
  const b = await page.locator("#instrument").boundingBox();
  await page.mouse.move(b.x + b.width * .42, b.y + b.height * .50); await page.mouse.down();
  await page.mouse.move(b.x + b.width * .67, b.y + b.height * .33, { steps: 12 }); await page.mouse.up();
  assert.ok((await state()).traces.length > 0); record("real pointer drag leaves traces");
  await next(); await next();
  const cutBox = await page.locator("#instrument").boundingBox();
  await page.mouse.move(cutBox.x + cutBox.width * .32, cutBox.y + cutBox.height * .35); await page.mouse.down();
  await page.mouse.move(cutBox.x + cutBox.width * .68, cutBox.y + cutBox.height * .65, { steps: 16 }); await page.mouse.up();
  assert.equal((await state()).scars.length, 1); record("real pointer cut adds counterexample");
  await page.locator("#reset").click();
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(4000);
  assert.equal(await stage(), "0");
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await shot("mobile"); record("390px entry layout");
  await page.setViewportSize({ width: 1280, height: 600 }); await settle();
  await shot("short");
  await page.locator("#primary-action").scrollIntoViewIfNeeded();
  const button = await page.locator("#primary-action").boundingBox();
  assert.ok(button.y >= 0 && button.y + button.height <= 601); record("short viewport controls scroll into view");
  await page.emulateMedia({ reducedMotion: "reduce" });
  assert.ok(await page.locator("#app").evaluate(el => el.classList.contains("reduced-motion")));
  for (let i = 0; i < 5; i++) await next();
  assert.equal(await stage(), "4");
  await shot("reduced"); record("reduced-motion complete journey");
  await page.setViewportSize({ width: 360, height: 740 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await shot("mobile-final"); record("360px completion layout");
  await page.setViewportSize({ width: 320, height: 568 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)); record("320px no horizontal overflow");
  const touchContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: "reduce" });
  const touch = await touchContext.newPage(); observe(touch);
  await touch.goto("http://127.0.0.1:4181", { waitUntil: "networkidle" });
  const touchBox = await touch.locator("#instrument").boundingBox();
  await touch.touchscreen.tap(touchBox.x + touchBox.width * .6, touchBox.y + touchBox.height * .5);
  assert.equal(await touch.locator("#trace-total").textContent(), "01");
  record("touch input");
  await touch.locator("#primary-action").tap(); await touch.locator("#primary-action").tap();
  const cdp = await touchContext.newCDPSession(touch);
  const tb = await touch.locator("#instrument").boundingBox();
  const x = tb.x + tb.width * .3, y = tb.y + tb.height * .4;
  await cdp.send("Input.dispatchTouchEvent", { type: "touchStart", touchPoints: [{ x, y }] });
  await cdp.send("Input.dispatchTouchEvent", { type: "touchMove", touchPoints: [{ x: x + tb.width * .3, y: y + 30 }] });
  await cdp.send("Input.dispatchTouchEvent", { type: "touchEnd", touchPoints: [] });
  assert.equal(await touch.evaluate(() => JSON.parse(localStorage.getItem("astra-unfinished-form-v1")).scars.length), 1);
  record("touch swipe creates fracture");
  const portable = await context.newPage(); observe(portable);
  await portable.goto(new URL("../outputs/unfinished-form.html", import.meta.url).href, { waitUntil: "load" });
  assert.equal(await portable.locator("#threads path").count(), 96);
  await portable.locator("#instrument").focus(); await portable.keyboard.press("ArrowLeft");
  assert.equal(await portable.locator("#trace-total").textContent(), "01"); record("offline portable HTML executes");
  await portable.locator("#about-open").click(); assert.ok(await portable.locator("#about-dialog").evaluate(el => el.open));
  await portable.keyboard.press("Escape"); assert.ok(!(await portable.locator("#about-dialog").evaluate(el => el.open))); record("help dialog and Escape");
  const blocked = await context.newPage(); observe(blocked);
  await blocked.addInitScript(() => { Object.defineProperty(window, "localStorage", { get() { throw new DOMException("Blocked", "SecurityError"); } }); });
  await blocked.goto("http://127.0.0.1:4181");
  for (let i = 0; i < 5; i++) await blocked.locator("#primary-action").click();
  assert.equal(await blocked.locator("#app").getAttribute("data-stage"), "4"); record("storage-disabled journey");
  assert.deepEqual(errors, []); record("browser console and page errors", "zero errors across tested pages");
} catch (error) {
  rows.push({ name: "failure", passed: false, detail: error.stack });
  console.error(error.stack); process.exitCode = 1;
} finally {
  await browser?.close(); server.kill();
  await writeFile(path.join(output, "production-results.json"), JSON.stringify({ passed: rows.every(r => r.passed), tests: rows, errors }, null, 2));
  await writeFile(path.join(output, "production-test.log"), rows.map(r => `${r.passed ? "PASS" : "FAIL"} ${r.name}: ${r.detail}`).join("\n"));
}
